### ISSUE TITLE
0.4.13 - Beta bug

### ISSUE THREAD

**Issue by tsakal** [pytesNET/tail.DateTime#43]
Hello.

Testing the demo page https://github.pytes.net/tail.DateTime/, I found that when changing the time (with the arrows), the selected day moves forward or backward.
Still in my own space at day selection, I have as a result, in the input field, the date and zero for time (YYYY-MM-DD 00:00:00).

Evangelos

**Comment by SamBrishes** [comment]
Hello,

thanks for mention this issue. Please try out the new [master branch](https://github.com/pytesNET/tail.DateTime/zipball/master) which should fix this bug.

Sincerely,
Sam.

**Comment by wtfdanny** [comment]
@SamBrishes I'm experiencing this issue with the latest version as well. I've also noticed, that clicking on a date will set the input fields time to 00:00:00 -- as far as I can recall, the last version I used (probably 2-3 releases old) it would retain the time input from the dialog > input field.

![1pff](https://user-images.githubusercontent.com/1396572/61914972-55bb3c80-aef7-11e9-8466-53e31ae16f62.gif)

**Comment by SamBrishes** [comment]
Hellow,

thanks for your comment @wtfdanny. Could you please provide me the configuration you use for this DateTime calendar script? Would be a great help. It's also really strange, that you have an enabled AM/PM switch and still showing 15 'Hours' (which shouldn't be possible on the 12-hours format :D). I guess that's relevant for this issue.

Thanks, and I really like this dark color.

Sincerely,
Sam.

**Comment by wtfdanny** [comment]
@SamBrishes now that you mention it (24h format) that may be part of the issue. I updated earlier and didn’t get too far into reconfiguring the time formatting. I’ll have to retest tomorrow with the time format corrected.

Here’s my config —

`
function createPicker(element) {
    return tail.DateTime(element, {
        animate: true,
        classNames: false,
        closeButton: true,
        dateFormat: "YYYY-mm-dd",
        dateStart: false,
        dateRanges: [],
        dateBlacklist: true,
        dateEnd: false,
        locale: "en",
        position: "right",
        rtl: "auto",
        startOpen: false,
        stayOpen: false,
        time12h: true,
        timeFormat: "HH:ii:ss",
        timeHours: true,
        timeMinutes: true,
        timeSeconds: true,
        timeIncrement: true,
        timeStepHours: 1,
        timeStepMinutes: 1,
        timeStepSeconds: 1,
        today: true,
        tooltips: [],
        viewDefault: "days",
        viewDecades: false,
        viewYears: false,
        viewMonths: true,
        viewDays: true,
        weekStart: 1
    });
}
`

**Comment by RobEasthope** [comment]
Just pulled the latest version off master and the issue is still occuring.

**Comment by tsakal** [comment]
I have tested this fix : https://github.com/pytesNET/tail.DateTime/issues/62 and it works fine.

Regards
Evangelos

**Comment by RobEasthope** [comment]
Odd, for what it's worth, I'll try and describe out use case in case it helps.

We need to stick an unknown number of fields into a form via a CMS backend. The options thus far are two types of field - one selecting both the date and time and the other solely using the date picker.

Our testing seems to generate the issue only within certain ranges of hour values which may explain our different results.

**Comment by MartijnHarmenzon** [comment]
I can also confirm fix #62 works. When will this be implemented?
